AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI Lambda PowerTools Example

Parameters:
  Stage:
    Type: String
    Default: dev

Resources:
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: 'id'
        Type: String
  
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      MemorySize: 128
      CodeUri: src
      Handler: app.handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          GATEWAY_STAGE_NAME: !Ref Stage
          POWERTOOLS_SERVICE_NAME: FastAPIPowerToolsExample
          POWERTOOLS_METRICS_NAMESPACE: FastAPINamespace
      Events:
        DefaultEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /{proxy+}
            Method: ANY

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      TracingEnabled: true

Outputs:
  ApiUrl:
    Description: URL of the API
    Value:
      Fn::Sub: 'https://${RestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${Stage}'
